Vyos

diff --git a/.github/workflows/check-pr-message.yml b/.github/workflows/check-pr-message.yml
--- a/.github/workflows/check-pr-message.yml
+++ b/.github/workflows/check-pr-message.yml
@@ -32,6 +32,7 @@
         - name: Check the PR title
           timeout-minutes: 2
           id: check_pr_title
+          continue-on-error: true
           run: |
             # ./reusable-actions/scripts/check-pr-title-and-commit-messages.py '${{ github.event.pull_request.url }}'
             # output=$(./reusable-actions/scripts/check-pr-title-and-commit-messages.py '${{ github.event.pull_request.url }}' 2>&1)
@@ -42,6 +43,14 @@
             #   exit 1
             # fi
 
+            # output=$(./reusable-actions/scripts/check-pr-title-and-commit-messages.py '${{ github.event.pull_request.url }}' 2>&1 || true)
+            # output_b64=$(echo "$output" | base64 -w 0)
+            # echo "error_message_b64=$output_b64" >> $GITHUB_ENV
+            # if [ -n "$output" ]; then
+            #   echo "::error ::$output"
+            #   exit 1
+            # fi
+
             output=$(./reusable-actions/scripts/check-pr-title-and-commit-messages.py '${{ github.event.pull_request.url }}' 2>&1 || true)
             output_b64=$(echo "$output" | base64 -w 0)
             echo "error_message_b64=$output_b64" >> $GITHUB_ENV
@@ -49,10 +58,11 @@
               echo "::error ::$output"
               exit 1
             fi
+
           shell: bash
 
         - name: Decode error message
-          if: failure()
+          # if: failure()
           id: decode_error_message
           run: |
             error_message=$(echo "${{ env.error_message_b64 }}" | base64 --decode)
