SoverscampVyos

diff --git a/.github/workflows/check-unused-imports.yml b/.github/workflows/check-unused-imports.yml
--- a/.github/workflows/check-unused-imports.yml
+++ b/.github/workflows/check-unused-imports.yml
@@ -22,31 +22,31 @@ jobs:
       - name: Analysing the code with pylint
         run: | 
           pylint_files=$(git ls-files *.py src/migration-scripts)
-          pylint --disable=all --enable=W0611 $pylint_files --output-format=json > pylint_output.json || true
+          pylint --disable=all --enable=W0611 $pylint_files --output-format=json
 
-          output=$(cat pylint_output.json | xargs)
-          echo "Step1 $output"
+          # output=$(cat pylint_output.json | xargs)
+          # echo "Step1 $output"
 
-          if [ -s pylint_output.json ]; then
-            # echo "Pylint detected issues with unused imports."
-            jq '.' pylint_output.json
-            output=$(jq -r '.[] | "\(.path):\(.message) (\(.symbol)) at line \(.line)"' pylint_output.json)
-            # echo "error_message=${output}" >> $GITHUB_ENV
-            echo "error_message=Pylint detected issues with unused imports" >> $GITHUB_ENV
-            echo "$output"
-            # echo "::error ::Unused imports detected."
-            exit 1
-          else
-            echo "No issues with unused imports."
-            echo "error_message=No issues in unused-imports" >> $GITHUB_ENV
-          fi
+          # if [ -s pylint_output.json ]; then
+          #   # echo "Pylint detected issues with unused imports."
+          #   jq '.' pylint_output.json
+          #   output=$(jq -r '.[] | "\(.path):\(.message) (\(.symbol)) at line \(.line)"' pylint_output.json)
+          #   # echo "error_message=${output}" >> $GITHUB_ENV
+          #   echo "error_message=Pylint detected issues with unused imports" >> $GITHUB_ENV
+          #   echo "$output"
+          #   # echo "::error ::Unused imports detected."
+          #   exit 1
+          # else
+          #   echo "No issues with unused imports."
+          #   echo "error_message=No issues in unused-imports" >> $GITHUB_ENV
+          # fi
            
-      - name: Add PR comment
-        if: always()
-        uses: mshick/add-pr-comment@v2
-        with:
-          message: |-
-            ${{ env.error_message == 'No issues in unused-imports' && '👍' || '❌' }}
-            ${{ env.error_message }}
-          message-id: "UNUSED_IMPORTS_VALIDATION"
-          allow-repeats: false
+      # - name: Add PR comment
+      #   if: always()
+      #   uses: mshick/add-pr-comment@v2
+      #   with:
+      #     message: |-
+      #       ${{ env.error_message == 'No issues in unused-imports' && '👍' || '❌' }}
+      #       ${{ env.error_message }}
+      #     message-id: "UNUSED_IMPORTS_VALIDATION"
+      #     allow-repeats: false
