Vyos

diff --git a/.github/workflows/check-unused-imports.yml b/.github/workflows/check-unused-imports.yml
--- a/.github/workflows/check-unused-imports.yml
+++ b/.github/workflows/check-unused-imports.yml
@@ -24,14 +24,12 @@ jobs:
           pylint_files=$(git ls-files *.py src/migration-scripts)
           output=$(pylint --disable=all --enable=W0611 $pylint_files 2>&1 | awk 'BEGIN { ORS = " " } { print }' || true)
           echo "$output"
-          if [[ -n "$output" ]]; then
-            if [[ "$output" != *"------------------------------------ Your code has been rated at 10.00/10"* ]]; then
-              echo "error_message=$output" >> $GITHUB_ENV
-              echo "$output"
-              exit 1
-            else
-              echo "error_message=No issues in unused-imports" >> $GITHUB_ENV
-            fi
+          if [[ "$output" == *"------------------------------------ Your code has been rated at 10.00/10"* ]]; then
+            echo "error_message=No issues in unused-imports" >> $GITHUB_ENV
+          else
+            echo "error_message=$output" >> $GITHUB_ENV
+            echo "$output"
+            exit 1
           fi
 
       - name: Add PR comment
