SoverscampVyos

diff --git a/.github/workflows/check-unused-imports.yml b/.github/workflows/check-unused-imports.yml
--- a/.github/workflows/check-unused-imports.yml
+++ b/.github/workflows/check-unused-imports.yml
@@ -21,34 +21,29 @@ jobs:
 
       - name: Analysing the code with pylint
         run: | 
-          # pylint_files=$(git ls-files *.py src/migration-scripts)
-          # pylint_files=src/migration-scripts/*.py
-          pylint --disable=all --enable=W0611 src/migration-scripts/*.py --output-format=json
-          # pylint --disable=all --enable=W0611 $pylint_files --output-format=json
-
-          # output=$(cat pylint_output.json | xargs)
-          # echo "Step1 $output"
-
-          # if [ -s pylint_output.json ]; then
-          #   # echo "Pylint detected issues with unused imports."
-          #   jq '.' pylint_output.json
-          #   output=$(jq -r '.[] | "\(.path):\(.message) (\(.symbol)) at line \(.line)"' pylint_output.json)
-          #   # echo "error_message=${output}" >> $GITHUB_ENV
-          #   echo "error_message=Pylint detected issues with unused imports" >> $GITHUB_ENV
-          #   echo "$output"
-          #   # echo "::error ::Unused imports detected."
-          #   exit 1
-          # else
-          #   echo "No issues with unused imports."
-          #   echo "error_message=No issues in unused-imports" >> $GITHUB_ENV
-          # fi
+          pylint_files=$(git ls-files *.py src/migration-scripts)
+          set +e
+          output=$(pylint --disable=all --enable=W0611 $pylint_files 2>&1)
+          exit_code=$?
+          set -e
+          if [[ $exit_code -eq 0 ]]; then
+            echo "error_message=No issues in unused-imports" >> $GITHUB_ENV
+            echo "No issues in unused-imports"
+          else
+            output=$(echo "$output" | xargs)
+            output=${output//"------------------------------------ Your code has been rated at 10.00/10"/}
+            output=${output//"*"/}
+            echo "$output" 
+            echo "error_message=${output//$'\n'/. }" >> $GITHUB_ENV 
+            exit 1
+          fi
            
-      # - name: Add PR comment
-      #   if: always()
-      #   uses: mshick/add-pr-comment@v2
-      #   with:
-      #     message: |-
-      #       ${{ env.error_message == 'No issues in unused-imports' && '👍' || '❌' }}
-      #       ${{ env.error_message }}
-      #     message-id: "UNUSED_IMPORTS_VALIDATION"
-      #     allow-repeats: false
+      - name: Add PR comment
+        if: always()
+        uses: mshick/add-pr-comment@v2
+        with:
+          message: |-
+            ${{ env.error_message == 'No issues in unused-imports' && '👍' || '❌' }}
+            ${{ env.error_message }}
+          message-id: "UNUSED_IMPORTS_VALIDATION"
+          allow-repeats: false
