Vyos

diff --git a/.github/workflows/check-pr-message.yml b/.github/workflows/check-pr-message.yml
--- a/.github/workflows/check-pr-message.yml
+++ b/.github/workflows/check-pr-message.yml
@@ -35,15 +35,15 @@
           # continue-on-error: true
           run: |
             # ./reusable-actions/scripts/check-pr-title-and-commit-messages.py '${{ github.event.pull_request.url }}'
-            output=$(./reusable-actions/scripts/check-pr-title-and-commit-messages.py '${{ github.event.pull_request.url }}' 2>&1)
-            echo "$output"            
-            # output=$(./reusable-actions/scripts/check-pr-title-and-commit-messages.py '${{ github.event.pull_request.url }}' 2>&1)
-            # echo "$output"
-            # if [ -n "$output" ]; then
-            #   echo "::error ::$output"
-            #   echo "error_message=$output" >> $GITHUB_ENV
-            #   exit 1
-            # fi
+            # output=$(./reusable-actions/scripts/check-pr-title-and-commit-messages.py '${{ github.event.pull_request.url }}' 2>&1)            
+            output=$(./reusable-actions/scripts/check-pr-title-and-commit-messages.py '${{ github.event.pull_request.url }}' 2>&1 || true)
+            echo "$output"
+            if [ -n "$output" ]; then
+              echo "::error ::$output"
+              # Set an output for the step
+              echo " ::set-output name=error_message::$output"
+              exit 1
+            fi
           shell: bash
 
         - name: Add PR comment
