.github

diff --git a/.github/workflows/check-unused-imports.yml b/.github/workflows/check-unused-imports.yml
--- a/.github/workflows/check-unused-imports.yml
+++ b/.github/workflows/check-unused-imports.yml
@@ -1,49 +1,101 @@
-name: Check for unused imports using Pylint 
+name: Validate python code using black and ruff
+
 on:
   workflow_call:
+    inputs:
+      base_ref:
+        required: true
+        type: string
+      head_ref:
+        required: true
+        type: string
+
 jobs:
-  check-unused-imports:
+  lint-and-format:
     runs-on: ubuntu-latest
+
     steps:
-      - uses: actions/checkout@v3
-      - name: Set up Python
-        uses: actions/setup-python@v3
-        with:
-          python-version: 3.11
-      - name: Install dependencies
-        run: |
-          python -m pip install --upgrade pip
-          pip install pylint
-      - name: Analysing the code with pylint
-        run: | 
-          pylint_files=$(git ls-files *.py src/migration-scripts)
-          set +e
-          output=$(pylint --disable=all --enable=W0611 --output-format=json $pylint_files 2>&1)
-          exit_code=$?
-          set -e
-          if [[ $exit_code -eq 0 ]]; then
-            echo "error_message=No issues in unused-imports" >> $GITHUB_ENV
-            echo "No issues in unused-imports"
-          else
+    - name: Checkout code
+      uses: actions/checkout@v3
 
-            formatted_output=$(echo "$output" | jq -r '.[] | "\(.type): \(.message) in \(.path):\(.line)"')
-            echo "$formatted_output"
+    - name: Set up Python
+      uses: actions/setup-python@v4
+      with:
+        python-version: '3.x'
 
-            echo "error_message<<EOF" >> $GITHUB_ENV
-            echo "$formatted_output" | while IFS= read -r line; do
-              echo "$line"
-            done >> $GITHUB_ENV
-            echo "EOF" >> $GITHUB_ENV
-          
-            exit 1
+    - name: Install dependencies
+      run: |
+        pip install black ruff
+
+    - name: Get list of modified Python files
+      id: git_diff
+      run: |
+        BASE_REF=${{ inputs.base_ref }}
+        HEAD_REF=${{ inputs.head_ref }}
+
+        echo "Base ref: $BASE_REF"
+        echo "Head ref: $HEAD_REF"
+        
+        if [ -z "$BASE_REF" ] || [ -z "$HEAD_REF" ]; then
+          echo "Base and head refs must be specified."
+          exit 1
+        fi
+        
+        git fetch origin $BASE_REF --depth=1
+        git fetch origin $HEAD_REF --depth=1
+
+        # Check if branches have a common ancestor
+        if ! git merge-base --is-ancestor origin/$BASE_REF origin/$HEAD_REF; then
+          echo "Branches $BASE_REF and $HEAD_REF do not have a common ancestor."
+          # Handle the case where there is no common ancestor
+          git diff --name-only origin/$BASE_REF origin/$HEAD_REF -- '*.py' > modified_files.txt
+        else
+          git diff --name-only origin/$BASE_REF...origin/$HEAD_REF -- '*.py' > modified_files.txt
+        fi
+
+    - name: Check contents of modified_files.txt
+      run: |
+        echo "Modified files:"
+        cat modified_files.txt
+
+    - name: Check formatting and linting
+      id: check_formatting_and_linting
+      run: |
+        if [ -s modified_files.txt ]; then
+          black_failed=false
+          ruff_failed=false
+          while IFS= read -r file; do
+            if [ -f "$file" ]; then
+              black --check "$file" || black_failed=true
+              ruff check "$file" || ruff_failed=true
+            else
+              echo "File $file does not exist."
+            fi
+          done < modified_files.txt
+          if [ "$black_failed" = true ]; then
+            echo "black_failed=true" >> $GITHUB_ENV
           fi
-           
-      - name: Add PR comment
-        if: always()
-        uses: mshick/add-pr-comment@v2
-        with:
-          message: |-
-            ${{ env.error_message == 'No issues in unused-imports' && '👍' || '❌' }}
-            ${{ env.error_message }}
-          message-id: "UNUSED_IMPORTS_VALIDATION"
-          allow-repeats: false
+          if [ "$ruff_failed" = true ]; then
+            echo "ruff_failed=true" >> $GITHUB_ENV
+          fi
+        else
+          echo "No Python files modified"
+        fi
+
+    - name: Determine result
+      id: determine_result
+      run: |
+        if [ "${{ env.black_failed }}" == "true" ] || [ "${{ env.ruff_failed }}" == "true" ]; then
+          echo "no_issues=false" >> $GITHUB_ENV
+        else
+          echo "no_issues=true" >> $GITHUB_ENV
+        fi
+
+    - name: Add PR comment with results
+      if: always()
+      uses: mshick/add-pr-comment@v2
+      with:
+        repo-token: ${{ secrets.GITHUB_TOKEN }}
+        message: ${{ env.no_issues == 'true' && '👍\nNo Formatting/Linting issue found in python files' || '❌\nIssues found in formatting/linting' }}
+        message-id: "FORMATTING_VALIDATION"
+        allow-repeats: false
